name: WhatsApp Follow-up Bot

on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:

jobs:
  send-messages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run WhatsApp Bot Script
        run: node bot.js
        env:
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          PHONE_ID: ${{ secrets.PHONE_ID }}
          META_TOKEN: ${{ secrets.META_TOKEN }}
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
